version: '3.8'

services:

  vault-server:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    restart: always
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul-server-backend

  consul-server-backend:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/consul-config.json
    restart: always
    volumes:
      - ./consul/config/consul-config.json:/consul/config/consul-config.json
      - consul-backend:/consul/data

  consul-worker:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -server -join consul-server-backend -config-file=/consul/config/consul-config.json
    restart: always
    volumes:
      - ./consul/config/consul-config.json:/consul/config/consul-config.json
    depends_on:
      - consul-server-backend