version: '3.6'

services:

  vault-server:
    image: 'vault'
    init: true
    container_name: vault-server
    ports:
      - 8200:8200
    restart: always
    networks:
      - consul_vault
    command:
      - "sh"
      - "-c"
      - |
        set -ex
        export IP=$$(ip -o ro get $$(ip ro | awk '$$1 == "default" { print $$3 }') | awk '{print $$5}')
        export VAULT_API_ADDR="http://$${IP}:8200" VAULT_CLUSTER_ADDR="https://$${IP}:8201"
        exec vault server -config=/vault/config
    #set scale: 3 for HA configuration
    scale: 1
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_LOCAL_CONFIG: >-
        {
            "ui": true,
            "backend": {
                "consul": {
                    "address": "consul-vault-backend-leader:8500",
                    "path": "vault",
                    "scheme": "http"
                }
            },
            "default_lease_ttl": "168h",
            "listener": {
                "tcp": {
                    "address": "0.0.0.0:8200",
                    "tls_disable": "1"
                }
            },
            "max_lease_ttl": "720h"
        }
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul-vault-backend-worker

  consul-vault-backend-leader:
    container_name: consul-vault-backend-leader
    ports:
      - 8500:8500
    image: 'consul'
    init: true
    command: 'agent -datacenter docker -server -bootstrap-expect 1 -disable-host-node-id -client 0.0.0.0 -ui -data-dir /consul/data'
    healthcheck:
      test: ['CMD', '/bin/sh', '-c', 'curl -sfLo /dev/null http://127.0.0.1:8500/v1/health/node/$$HOSTNAME']
    scale: 1
    networks:
      - consul_vault
    volumes:
      - consul-vault-backend-volume:/consul/data
    restart: always

  consul-vault-backend-worker:
    image: 'consul'
    init: true
    entrypoint: ''
    command:
      - /bin/sh
      - -c
      - |
        set -ex
        until apk update; do sleep 3; done
        until apk add bind-tools; do sleep 3; done
        until dig +short consul-vault-backend-leader; do sleep 1; done
        docker-entrypoint.sh agent -datacenter docker -server -join consul-vault-backend-leader -disable-host-node-id -client 0.0.0.0 -ui
    scale: 2
    networks:
      - consul_vault
    restart: always
    depends_on:
      - consul-vault-backend-leader

networks:
  consul_vault:
    driver: bridge

volumes:
  consul-vault-backend-volume: