version: '3.8'

volumes:
  consul-server:

networks:
  vault-network:
    driver: bridge

services:

  vault-server:
    container_name: vault-server
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    restart: always
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul-server-backend
    networks:
      - vault-network

  consul-server-backend:
    container_name: consul-server-backend
    init: true
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/consul-config.json
    restart: always
    volumes:
      - ./consul/config/consul-config.json:/consul/config/consul-config.json
      - ./consul/config/certs/:/consul/config/certs/:ro
      - ./consul/config/acls/:/consul/config/acls/
      - consul-server:/consul/data
    networks:
      - vault-network

  consul-worker:
    init: true
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -server -join consul-server-backend -disable-host-node-id -client 0.0.0.0 -ui -config-file=/consul/config/consul-config-worker.json
    restart: always
    scale: 2
    networks:
      - vault-network
    volumes:
      - ./consul/config/consul-config-worker.json:/consul/config/consul-config-worker.json
      - ./consul/config/certs/:/consul/config/certs/:ro
      - ./consul/config/acls/:/consul/config/acls/
    depends_on:
      - consul-server-backend